import { staticFile } from "remotion";
import type { Story } from "../items/story";

// A real (fictional-but-specific) screenshot, per Phase 2's P2-7: a gradient-rectangle placeholder
// reads as fake UI in a demo the same way ScreenPlaceholder does.
const SHOT = staticFile("reelcn-demo/screenshots/fictional-analytics.webp");

// Generated by scripts/demo-audio.ts; 4 seconds long.
const CLIP = staticFile("reelcn-demo/clip.mp4");

/** The Storyboard composition's default props, and its first demo: a short launch story with no assets. */
export const sampleStory: Story = {
  scenes: [
    {
      type: "title",
      kicker: "Introducing",
      title: "Relay",
      subtitle: "Release notes your users actually read",
      background: "gradient-mesh",
    },
    {
      type: "bullets",
      title: "Why teams switch",
      items: [
        { text: "Write once", detail: "Draft in Markdown and publish everywhere." },
        { text: "Ship on merge", detail: "Every merged pull request becomes a line." },
        { text: "See who read it", detail: "Opens and clicks for every release." },
      ],
    },
    { type: "stat", label: "Teams shipping with Relay", value: 4200, suffix: "+", delta: 18 },
    { type: "cta", title: "Start free today", button: "Get Relay", url: "relay.example.com", background: "spotlight" },
  ],
};

/** All fifteen scene types, five to a story and 2.5 s each, so contact sheets and smoke stills show every one. */
export const sceneTour: Story[] = [
  {
    defaults: { transition: "slice-slide" },
    scenes: [
      { type: "title", kicker: "Scene tour", title: "Fifteen scene types", subtitle: "Five per story", duration: 2.5 },
      {
        type: "text",
        text: "Text scenes paint chosen words in the accent",
        accent: ["accent"],
        background: "grid",
        duration: 2.5,
      },
      {
        type: "bullets",
        title: "Bullets",
        items: [
          { text: "Stagger in", detail: "One card after another." },
          { text: "Reflow", detail: "Rows in landscape, a column in portrait." },
        ],
        duration: 2.5,
      },
      { type: "image", src: SHOT, caption: "Image scenes drift slowly", duration: 2.5 },
      { type: "video", src: CLIP, muted: true, duration: 2.5 },
    ],
  },
  {
    defaults: { transition: "card-push" },
    scenes: [
      { type: "device", device: "phone", src: SHOT, duration: 2.5 },
      {
        type: "code",
        title: "add.ts",
        language: "ts",
        code: "export const add = (a: number, b: number) => a + b;",
        duration: 2.5,
      },
      {
        type: "terminal",
        lines: [
          { type: "command", text: "npx shadcn add @reelcn/storyboard" },
          { type: "output", text: "Created src/reelcn/storyboard.tsx" },
        ],
        duration: 2.5,
      },
      {
        type: "chart",
        kind: "bar",
        title: "Renders per day",
        data: [
          { label: "Mon", value: 12 },
          { label: "Tue", value: 30 },
          { label: "Wed", value: 22 },
          { label: "Thu", value: 41 },
        ],
        duration: 2.5,
      },
      { type: "stat", label: "Frames rendered", value: 128400, delta: 24, duration: 2.5 },
    ],
  },
  {
    defaults: { transition: "light-flash" },
    scenes: [
      {
        type: "quote",
        quote: "We cut our launch video from two weeks to one afternoon.",
        name: "Maya Chen",
        role: "Head of product, Northwind",
        duration: 2.5,
      },
      {
        type: "post",
        name: "Northwind",
        handle: "@northwind",
        text: "Shipped the new dashboard today. Faster, calmer, and it finally works on phones.",
        metrics: { likes: 1240, comments: 86, shares: 41 },
        duration: 2.5,
      },
      {
        type: "cta",
        title: "Try it today",
        button: "Get started",
        url: "relay.example.com",
        background: "spotlight",
        duration: 2.5,
      },
      { type: "logo", text: "Northwind", background: "gradient-mesh", duration: 2.5 },
      {
        type: "split",
        labels: ["Before", "After"],
        left: { type: "image", src: SHOT },
        right: { type: "device", device: "browser", src: CLIP, url: "relay.example.com" },
        duration: 2.5,
      },
    ],
  },
];
