// Generated by scripts/build-motion-tokens.ts from tokens.json. Do not edit.
pub const DURATION_ENTER: f32 = 0.6;
pub const DURATION_EXIT: f32 = 0.35;
pub const DURATION_TRANSITION: f32 = 0.5;
pub const EASE_SMOOTH: (f32, f32, f32, f32) = (0.16, 1.0, 0.3, 1.0);
pub const EASE_SNAPPY: (f32, f32, f32, f32) = (0.2, 0.9, 0.1, 1.0);
pub const EASE_GENTLE: (f32, f32, f32, f32) = (0.25, 0.1, 0.25, 1.0);
pub const EASE_LINEAR: (f32, f32, f32, f32) = (0.0, 0.0, 1.0, 1.0);
pub const EASE_EXIT: (f32, f32, f32, f32) = (0.23, 1.0, 0.32, 1.0);
pub const SPRING_DAMPING: f32 = 15.0;
pub const SPRING_STIFFNESS: f32 = 170.0;
pub const SPRING_MASS: f32 = 0.9;
pub const STAGGER_GAP: f32 = 0.08;
pub const STAGGER_MAX_TOTAL: f32 = 0.6;
pub const OVERLAP: f32 = 0.25;
pub const MUSIC_VOLUME: f32 = 0.25;
pub const SFX_VOLUME: f32 = 0.7;

/// Seconds at which beat `n` of a track lands.
pub fn beat_time(n: u32, bpm: f32, offset: f32) -> f32 {
    offset + (n as f32) * 60.0 / bpm
}
