// Generated by scripts/build-motion-tokens.ts from tokens.json. Do not edit.
export const motion = {
  "duration": {
    "enter": 0.6,
    "exit": 0.35,
    "transition": 0.5
  },
  "ease": {
    "smooth": [
      0.16,
      1,
      0.3,
      1
    ],
    "snappy": [
      0.2,
      0.9,
      0.1,
      1
    ],
    "gentle": [
      0.25,
      0.1,
      0.25,
      1
    ],
    "linear": [
      0,
      0,
      1,
      1
    ],
    "exit": [
      0.23,
      1,
      0.32,
      1
    ]
  },
  "spring": {
    "damping": 15,
    "stiffness": 170,
    "mass": 0.9
  },
  "stagger": {
    "gap": 0.08,
    "acceleration": 0.85,
    "maxTotal": 0.6
  },
  "overlap": 0.25,
  "reading": {
    "wordsPerSecond": 3,
    "holdFloor": 1
  },
  "tone": {
    "calm": {
      "holdScale": 1.3,
      "maxSounds": 3
    },
    "standard": {
      "holdScale": 1,
      "maxSounds": 5
    },
    "loud": {
      "holdScale": 1,
      "maxSounds": 9
    }
  },
  "audio": {
    "musicVolume": 0.25,
    "sfxVolume": 0.7,
    "fadeIn": 0.4,
    "fadeOut": 1,
    "beatTolerance": 0.05,
    "loudnessMin": -24,
    "loudnessMax": -12,
    "truePeakMax": -1,
    "beds": {
      "bed-calm": 100,
      "bed-standard": 120,
      "bed-loud": 150
    },
    "sfx": [
      "bell",
      "bubble",
      "camera-shutter",
      "chime",
      "click",
      "click-soft",
      "coin",
      "ding",
      "drop",
      "error",
      "glitch",
      "impact",
      "keypress",
      "notification",
      "pop",
      "pop-high",
      "rise",
      "riser-short",
      "sparkle",
      "success",
      "swipe",
      "swish",
      "swoosh",
      "tap",
      "thud",
      "tick",
      "transition-hit",
      "typing",
      "whoosh",
      "whoosh-soft"
    ]
  }
};

/** The spring as [time 0..1, value] pairs, for renderers with no spring of their own. */
export const springKeyframes = [[0,0],[0.042,0.112],[0.083,0.348],[0.125,0.602],[0.167,0.815],[0.208,0.965],[0.25,1.05],[0.292,1.086],[0.333,1.087],[0.375,1.071],[0.417,1.049],[0.458,1.027],[0.5,1.01],[0.542,0.999],[0.583,0.994],[0.625,0.992],[0.667,0.993],[0.708,0.994],[0.75,0.996],[0.792,0.998],[0.833,1],[0.875,1],[0.917,1.001],[0.958,1.001],[1,1]];

/** Seconds at which beat `n` of a track lands. */
export function beatTime(n, bpm, offset = 0) {
  return offset + (n * 60) / bpm;
}
