// Generated by scripts/build-motion-tokens.ts from tokens.json. Do not edit.
export const motion = {
  "duration": {
    "enter": 0.6,
    "exit": 0.35,
    "transition": 0.5
  },
  "ease": {
    "smooth": [
      0.16,
      1,
      0.3,
      1
    ],
    "snappy": [
      0.2,
      0.9,
      0.1,
      1
    ],
    "gentle": [
      0.25,
      0.1,
      0.25,
      1
    ],
    "linear": [
      0,
      0,
      1,
      1
    ],
    "exit": [
      0.23,
      1,
      0.32,
      1
    ]
  },
  "spring": {
    "damping": 15,
    "stiffness": 170,
    "mass": 0.9
  },
  "stagger": {
    "gap": 0.08,
    "acceleration": 0.85,
    "maxTotal": 0.6
  },
  "overlap": 0.25,
  "reading": {
    "wordsPerSecond": 3,
    "holdFloor": 1
  },
  "tone": {
    "calm": {
      "holdScale": 1.3,
      "maxSounds": 3
    },
    "standard": {
      "holdScale": 1,
      "maxSounds": 5
    },
    "loud": {
      "holdScale": 1,
      "maxSounds": 9
    }
  },
  "audio": {
    "musicVolume": 0.25,
    "sfxVolume": 0.7,
    "fadeIn": 0.4,
    "fadeOut": 1,
    "beatTolerance": 0.05,
    "loudnessMin": -24,
    "loudnessMax": -12,
    "truePeakMax": -1,
    "beds": {
      "bed-calm": 100,
      "bed-standard": 120,
      "bed-loud": 150
    },
    "sfx": [
      "bell",
      "bubble",
      "camera-shutter",
      "chime",
      "click",
      "click-soft",
      "coin",
      "ding",
      "drop",
      "error",
      "glitch",
      "impact",
      "keypress",
      "notification",
      "pop",
      "pop-high",
      "rise",
      "riser-short",
      "sparkle",
      "success",
      "swipe",
      "swish",
      "swoosh",
      "tap",
      "thud",
      "tick",
      "transition-hit",
      "typing",
      "whoosh",
      "whoosh-soft"
    ]
  }
} as const;

/** Seconds at which beat `n` of a track lands. */
export function beatTime(n: number, bpm: number, offset = 0): number {
  return offset + (n * 60) / bpm;
}
