// Generates the reelcn-motion token files from tokens.json, one per renderer.
// Run: node scripts/build-motion-tokens.ts   (pnpm registry:build runs it too; commit the result)
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const DIR = "skills/reelcn-motion/tokens";
const BANNER = "Generated by scripts/build-motion-tokens.ts from tokens.json. Do not edit.";

type Bezier = [number, number, number, number];
type Tokens = {
  duration: Record<string, number>;
  ease: Record<string, Bezier>;
  spring: { damping: number; stiffness: number; mass: number };
  stagger: { gap: number; acceleration: number; maxTotal: number };
  overlap: number;
  reading: { wordsPerSecond: number; holdFloor: number };
  tone: Record<string, { holdScale: number; maxSounds: number }>;
  audio: Record<string, unknown> & { beds: Record<string, number>; sfx: string[] };
};

/** The spring as [time 0..1, value] pairs, for renderers with no spring of their own. */
export function springKeyframes({ damping, stiffness, mass }: Tokens["spring"], points = 24): [number, number][] {
  // Semi-implicit Euler at 1ms steps until the spring rests within 0.1% of 1.
  const dt = 0.001;
  const path: number[] = [];
  let x = 0;
  let v = 0;
  let rest = 0;
  for (let i = 0; i < 5000 && rest < 100; i++) {
    v += ((-stiffness * (x - 1) - damping * v) / mass) * dt;
    x += v * dt;
    path.push(x);
    rest = Math.abs(x - 1) < 0.001 && Math.abs(v) < 0.01 ? rest + 1 : 0;
  }
  const round = (n: number) => Math.round(n * 1000) / 1000;
  const frames: [number, number][] = [[0, 0]];
  for (let p = 1; p < points; p++)
    frames.push([round(p / points), round(path[Math.floor((p / points) * (path.length - 1))])]);
  frames.push([1, 1]);
  return frames;
}

const snake = (name: string) => name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`).replace(/-/g, "_");
const kebab = (name: string) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

export function renderTs(tokens: Tokens): string {
  return `// ${BANNER}\nexport const motion = ${JSON.stringify(tokens, null, 2)} as const;\n\n/** Seconds at which beat \`n\` of a track lands. */\nexport function beatTime(n: number, bpm: number, offset = 0): number {\n  return offset + (n * 60) / bpm;\n}\n`;
}

export function renderJs(tokens: Tokens): string {
  return `// ${BANNER}\nexport const motion = ${JSON.stringify(tokens, null, 2)};\n\n/** The spring as [time 0..1, value] pairs, for renderers with no spring of their own. */\nexport const springKeyframes = ${JSON.stringify(springKeyframes(tokens.spring))};\n\n/** Seconds at which beat \`n\` of a track lands. */\nexport function beatTime(n, bpm, offset = 0) {\n  return offset + (n * 60) / bpm;\n}\n`;
}

export function renderCss(tokens: Tokens): string {
  const lines = [
    ...Object.entries(tokens.duration).map(([name, s]) => `  --reelcn-duration-${kebab(name)}: ${s}s;`),
    ...Object.entries(tokens.ease).map(([name, b]) => `  --reelcn-ease-${kebab(name)}: cubic-bezier(${b.join(", ")});`),
    `  --reelcn-stagger-gap: ${tokens.stagger.gap}s;`,
    `  --reelcn-overlap: ${tokens.overlap};`,
  ];
  return `/* ${BANNER} */\n:root {\n${lines.join("\n")}\n}\n`;
}

export function renderRs(tokens: Tokens): string {
  const f = (n: number) => (Number.isInteger(n) ? `${n}.0` : String(n));
  const lines = [
    ...Object.entries(tokens.duration).map(
      ([name, s]) => `pub const DURATION_${snake(name).toUpperCase()}: f32 = ${f(s)};`,
    ),
    ...Object.entries(tokens.ease).map(
      ([name, b]) => `pub const EASE_${snake(name).toUpperCase()}: (f32, f32, f32, f32) = (${b.map(f).join(", ")});`,
    ),
    `pub const SPRING_DAMPING: f32 = ${f(tokens.spring.damping)};`,
    `pub const SPRING_STIFFNESS: f32 = ${f(tokens.spring.stiffness)};`,
    `pub const SPRING_MASS: f32 = ${f(tokens.spring.mass)};`,
    `pub const STAGGER_GAP: f32 = ${f(tokens.stagger.gap)};`,
    `pub const STAGGER_MAX_TOTAL: f32 = ${f(tokens.stagger.maxTotal)};`,
    `pub const OVERLAP: f32 = ${f(tokens.overlap)};`,
    `pub const MUSIC_VOLUME: f32 = ${f(tokens.audio.musicVolume as number)};`,
    `pub const SFX_VOLUME: f32 = ${f(tokens.audio.sfxVolume as number)};`,
  ];
  return `// ${BANNER}\n${lines.join("\n")}\n\n/// Seconds at which beat \`n\` of a track lands.\npub fn beat_time(n: u32, bpm: f32, offset: f32) -> f32 {\n    offset + (n as f32) * 60.0 / bpm\n}\n`;
}

export function buildMotionTokens(dir = DIR): void {
  const tokens = JSON.parse(readFileSync(path.join(dir, "tokens.json"), "utf8")) as Tokens;
  writeFileSync(path.join(dir, "tokens.ts"), renderTs(tokens));
  writeFileSync(path.join(dir, "tokens.js"), renderJs(tokens));
  writeFileSync(path.join(dir, "tokens.css"), renderCss(tokens));
  writeFileSync(path.join(dir, "tokens.rs"), renderRs(tokens));
}

if (import.meta.main) {
  buildMotionTokens();
  console.log(`motion tokens written to ${DIR}`);
}
