// Generates the CC0 music beds with ffmpeg, and writes the licence manifest.
// Run: node scripts/music-build.ts   (writes music/*.mp3 + music/LICENSES.md; commit the result)
// Needs a system ffmpeg on PATH, as scripts/sfx-build.ts does.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = "music";
const TOKENS = "skills/reelcn-motion/tokens/tokens.json";
const BEATS = 48;

// ponytail: three synthesised beds, one chord each. Licensed or composed tracks when the ear trial says these read as a game.
const beds: { name: string; root: number; third: number; fifth: number; hat: number }[] = [
  { name: "bed-calm", root: 196.0, third: 246.94, fifth: 293.66, hat: 0.08 },
  { name: "bed-standard", root: 220.0, third: 277.18, fifth: 329.63, hat: 0.2 },
  { name: "bed-loud", root: 246.94, third: 311.13, fifth: 369.99, hat: 0.3 },
];

/** One bed: a kick on every beat, a hat between beats, a bass note every two beats, a held chord. Beat 0 lands at 0s. */
export function bedFilter(bed: (typeof beds)[number], bpm: number): string {
  const b = 60 / bpm;
  const d = (BEATS * b).toFixed(3);
  const kick = `aevalsrc='sin(2*PI*(50+70*exp(-mod(t,${b})*28))*mod(t,${b}))*exp(-mod(t,${b})*8)':d=${d}[kick]`;
  const hat = `anoisesrc=d=${d}:c=white:a=${bed.hat},highpass=f=7000,volume='exp(-mod(t+${b / 2},${b})*40)':eval=frame[hat]`;
  const pad = `aevalsrc='(0.2*sin(2*PI*${bed.root}*t)+0.16*sin(2*PI*${bed.third}*t)+0.16*sin(2*PI*${bed.fifth}*t))*(0.75+0.25*sin(2*PI*t/${8 * b}))':d=${d},lowpass=f=1400[pad]`;
  const bass = `aevalsrc='0.45*sin(2*PI*${bed.root / 2}*t)*exp(-mod(t,${2 * b})*2.5)':d=${d}[bass]`;
  return `${kick};${hat};${pad};${bass};[kick][hat][pad][bass]amix=inputs=4:duration=first:normalize=0`;
}

function main() {
  const tempos = (JSON.parse(readFileSync(TOKENS, "utf8")) as { audio: { beds: Record<string, number> } }).audio.beds;
  mkdirSync(OUT, { recursive: true });
  for (const bed of beds) {
    const bpm = tempos[bed.name];
    if (!bpm) throw new Error(`${bed.name}: no tempo in ${TOKENS}`);
    const seconds = (BEATS * 60) / bpm;
    const output = path.resolve(OUT, `${bed.name}.mp3`);
    try {
      execFileSync(
        "ffmpeg",
        [
          "-hide_banner",
          "-loglevel",
          "error",
          "-y",
          "-f",
          "lavfi",
          "-i",
          bedFilter(bed, bpm),
          "-af",
          `afade=t=out:st=${(seconds - 0.05).toFixed(3)}:d=0.05,loudnorm=I=-16:TP=-1.5:LRA=11`,
          "-ac",
          "1",
          "-ar",
          "44100",
          "-b:a",
          "128k",
          output,
        ],
        { stdio: ["ignore", "ignore", "inherit"] },
      );
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT")
        throw new Error("music:build needs ffmpeg on PATH. Install it, for example: brew install ffmpeg");
      throw err;
    }
    console.log(`ok   ${output}  ${bpm} BPM, ${seconds.toFixed(1)}s`);
  }
  writeFileSync(
    path.join(OUT, "LICENSES.md"),
    `# Music licences\n\nEvery track here is generated by \`scripts/music-build.ts\` with ffmpeg, so reelcn holds the rights and releases them under CC0-1.0. Re-run \`pnpm music:build\` to reproduce them.\n\nEach bed is ${BEATS} beats long, starts on beat 0 at 0s and targets -16 LUFS integrated.\n\n| File | Author | Licence | Source |\n|---|---|---|---|\n${beds
      .map(
        (bed) =>
          `| ${bed.name}.mp3 | reelcn | CC0-1.0 | generated by scripts/music-build.ts, ${tempos[bed.name]} BPM |`,
      )
      .join("\n")}\n`,
  );
  console.log(`${beds.length} beds and LICENSES.md written to ${OUT}`);
}

if (import.meta.main) main();
